import { supabase } from './supabase'
import { Task, TeamMember, Project, Organization } from '@/types'

// Organizations API
export const organizationsAPI = {
  // Get organization by ID
  async getById(id: string): Promise<Organization> {
    const { data, error } = await supabase
      .from('organizations')
      .select('*')
      .eq('id', id)
      .single()
    
    if (error) throw error
    return data
  },

  // Get organization by invite code
  async getByInviteCode(inviteCode: string): Promise<Organization> {
    const { data, error } = await supabase
      .from('organizations')
      .select('*')
      .eq('invite_code', inviteCode)
      .single()
    
    if (error) throw error
    return data
  },

  // Create organization
  async create(name: string, userId: string): Promise<Organization> {
    const { data, error } = await supabase
      .from('organizations')
      .insert({
        name,
        created_by: userId,
        invite_code: '' // Will be auto-generated by trigger
      })
      .select()
      .single()
    
    if (error) throw error
    return data
  },

  // Get user's organization
  async getUserOrganization(userId: string): Promise<Organization | null> {
    const { data, error } = await supabase
      .from('team_members')
      .select('organization_id')
      .eq('user_id', userId)
      .single()
    
    if (error) return null
    if (!data?.organization_id) return null

    return this.getById(data.organization_id)
  }
}

// Team Members API
export const teamAPI = {
  // Get all active team members for an organization
  async getAll(organizationId?: string): Promise<TeamMember[]> {
    let query = supabase
      .from('team_members')
      .select('*')
      .eq('is_active', true)
    
    // Filter by organization if provided
    if (organizationId) {
      query = query.eq('organization_id', organizationId)
    }
    
    const { data, error } = await query.order('name')
    
    if (error) throw error
    return data || []
  },

  // Create new team member
  async create(member: Omit<TeamMember, 'id' | 'created_at' | 'updated_at'>): Promise<TeamMember> {
    const { data, error } = await supabase
      .from('team_members')
      .insert(member)
      .select()
      .single()
    
    if (error) throw error
    return data
  },

  async delete(id: string): Promise<void> {
    const { error } = await supabase
      .from('team_members')
      .delete()
      .eq('id', id)
    
    if (error) throw error
  }
}

// Tasks API
export const tasksAPI = {
  // Get all tasks with assignee info for an organization
  async getAll(organizationId?: string): Promise<Task[]> {
    let query = supabase.from('tasks').select('*')
    
    // Filter by organization if provided
    if (organizationId) {
      query = query.eq('organization_id', organizationId)
    }
    
    const { data: tasks, error: tasksError } = await query.order('position')
    
    if (tasksError) throw tasksError
    
    // Fetch team members for the same organization
    let membersQuery = supabase.from('team_members').select('*')
    if (organizationId) {
      membersQuery = membersQuery.eq('organization_id', organizationId)
    }
    const { data: members } = await membersQuery
    
    // Map assignees to tasks
    const tasksWithAssignees = (tasks || []).map(task => ({
      ...task,
      assignee: task.assignee_id ? members?.find(m => m.id === task.assignee_id) : null
    }))
    
    return tasksWithAssignees
  },

  // Create new task
  async create(task: Omit<Task, 'id' | 'createdAt' | 'updatedAt'>): Promise<Task> {
    const { data, error } = await supabase
      .from('tasks')
      .insert(task)
      .select('*')
      .single()
    
    if (error) throw error
    
    // Fetch assignee separately if needed
    if (data.assignee_id) {
      const { data: assignee } = await supabase
        .from('team_members')
        .select('*')
        .eq('id', data.assignee_id)
        .single()
      
      return { ...data, assignee }
    }
    
    return { ...data, assignee: null }
  },

  // Update task
  async update(id: string, updates: Partial<Task>): Promise<Task> {
    const { data, error } = await supabase
      .from('tasks')
      .update({ ...updates, updated_at: new Date().toISOString() })
      .eq('id', id)
      .select('*')
      .single()
    
    if (error) throw error
    
    // Fetch assignee separately if needed
    if (data.assignee_id) {
      const { data: assignee } = await supabase
        .from('team_members')
        .select('*')
        .eq('id', data.assignee_id)
        .single()
      
      return { ...data, assignee }
    }
    
    return { ...data, assignee: null }
  },

  // Delete task
  async delete(id: string): Promise<void> {
    const { error } = await supabase
      .from('tasks')
      .delete()
      .eq('id', id)
    
    if (error) throw error
  },

  // Update task position and status (for drag and drop)
  async updatePosition(id: string, status: string, position: number): Promise<Task> {
    const { data, error } = await supabase
      .from('tasks')
      .update({ 
        status, 
        position, 
        updated_at: new Date().toISOString() 
      })
      .eq('id', id)
      .select('*')
      .single()
    
    if (error) throw error
    
    // Fetch assignee separately if needed
    if (data.assignee_id) {
      const { data: assignee } = await supabase
        .from('team_members')
        .select('*')
        .eq('id', data.assignee_id)
        .single()
      
      return { ...data, assignee }
    }
    
    return { ...data, assignee: null }
  }
}

// Projects API (for later)
export const projectsAPI = {
  async getAll(): Promise<Project[]> {
    const { data, error } = await supabase
      .from('projects')
      .select('*')
      .order('name')
    
    if (error) throw error
    return data || []
  }
}